[package]
name = "ferrum_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
anyhow = "1.0"
env_logger = "0.11.8"
log = "0.4"
pollster = "0.4.0"
bytemuck = "1.23.1"
egui = "0.31.1"
egui-wgpu = { version = "0.31.1",features = ["winit"] }
egui-winit = "0.31.1"
winit = "0.30.9"